export type SupportedLanguage = "en" | "hi" | "fr" | "es" | "zh" | "hinglish";

export interface TranslationDictionary {
  appName: string;
  subtitle: string;
  searchPlaceholder: string;
  synthesizeBtn: string;
  academicDesk: string;
  shareLinkBtn: string;
  controlCenter: string;
  researchDeskTab: string;
  prefTab: string;
  themeShift: string;
  themeDescription: string;
  scholarContact: string;
  scholarDescription: string;
  thanksTribute: string;
  thanksDetailed: string;
  commentsLabel: string;
  submitComments: string;
  commentsPlaceholder: string;
  recommendedTopics: string;
  exploreTab: string;
  chronologyTab: string;
  labLogTab: string;
  readingsTab: string;
  toastNoteSaved: string;
  toastFeedbackSaved: string;
  regeneratePortrait: string;
  generatePortrait: string;
  wikipediaBio: string;
  activeLanguage: string;
  selectFontLabel: string;
}

export const translations: Record<SupportedLanguage, TranslationDictionary> = {
  en: {
    appName: "Scientia Confluxus",
    subtitle: "Search a scientific anomaly, historical milestone, or physical formula to synthesize custom chronological dossiers and laboratory status logs.",
    searchPlaceholder: "Enter research topic (e.g., Quantum Gravity)...",
    synthesizeBtn: "Synthesize Dossier",
    academicDesk: "Academic Desk",
    shareLinkBtn: "Share Link",
    controlCenter: "Scientia Control Center",
    researchDeskTab: "Academic Desk",
    prefTab: "Preferences & Help",
    themeShift: "Background Theme Shifts",
    themeDescription: "Dynamically customize the entire color scheme of the application platform for comfortable day or night academic research:",
    scholarContact: "Scholar Contact",
    scholarDescription: "Connect directly with the Chief Archivist for collaborative submissions or dataset inquiries:",
    thanksTribute: "Thanks for using Scientia Confluxus!",
    thanksDetailed: "We are dedicated to building high-fidelity intellectual syntheses. Please share your suggestions or comments below so we can expand our scientific knowledge logs.",
    commentsLabel: "Write Comments & suggestions",
    submitComments: "Submit Comments",
    commentsPlaceholder: "Enter suggestions, errors detected, database ideas, or feature requests...",
    recommendedTopics: "Popular Scholarly Recommendations",
    exploreTab: "Explore Overview",
    chronologyTab: "Milestone Chronology",
    labLogTab: "Lab Status Log",
    readingsTab: "Literature Review",
    toastNoteSaved: "Research note captured successfully on draft stack.",
    toastFeedbackSaved: "Thanks for using! Your valuable feedback has been submitted successfully.",
    regeneratePortrait: "Re-generate Port",
    generatePortrait: "Gen Portrait",
    wikipediaBio: "Wikipedia Biography",
    activeLanguage: "Display Language",
    selectFontLabel: "Aesthetic Typography Font",
  },
  hi: {
    appName: "वैज्ञानिक संगम (Scientia Confluxus)",
    subtitle: "कस्टम कालानुक्रमिक डोजियर और प्रयोगशाला स्थिति लॉग को संश्लेषित करने के लिए वैज्ञानिक विसंगति, ऐतिहासिक मील के पत्थर या भौतिक सूत्र की खोज करें।",
    searchPlaceholder: "शोध विषय दर्ज करें (जैसे, क्वांटम गुरुत्वाकर्षण)...",
    synthesizeBtn: "दस्तावेज़ संश्लेषित करें",
    academicDesk: "अकादमिक डेस्क",
    shareLinkBtn: "लिंक साझा करें",
    controlCenter: "वैज्ञानिक नियंत्रण केंद्र",
    researchDeskTab: "अकादमिक डेस्क",
    prefTab: "प्राथमिकताएं और सहायता",
    themeShift: "पृष्ठभूमि थीम परिवर्तन",
    themeDescription: "आरामदायक दिन या रात के शैक्षणिक अनुसंधान के लिए एप्लिकेशन प्लेटफ़ॉर्म की संपूर्ण रंग योजना को गतिशील रूप से अनुकूलित करें:",
    scholarContact: "विद्वान संपर्क",
    scholarDescription: "सहयोगात्मक प्रस्तुतियाँ या डेटासेट पूछताछ के लिए सीधे मुख्य संग्रहकर्ता से जुड़ें:",
    thanksTribute: "वैज्ञानिक संगम का उपयोग करने के लिए धन्यवाद!",
    thanksDetailed: "हम उच्च-सत्यता बौद्धिक संश्लेषण के निर्माण के लिए समर्पित हैं। कृपया अपने सुझाव या टिप्पणियाँ नीचे साझा करें ताकि हम अपने वैज्ञानिक ज्ञान लॉग का विस्तार कर सकें।",
    commentsLabel: "टिप्पणियाँ और सुझाव लिखें",
    submitComments: "सुझाव प्रस्तुत करें",
    commentsPlaceholder: "सुझाव, पाई गई त्रुटियां, डेटाबेस विचार, या सुविधा अनुरोध दर्ज करें...",
    recommendedTopics: "लोकप्रिय शैक्षणिक अनुशंसाएँ",
    exploreTab: "समीक्षा का अन्वेषण करें",
    chronologyTab: "कालानुक्रमिक मील के पत्थर",
    labLogTab: "लैब स्थिति लॉग",
    readingsTab: "साहित्य की समीक्षा",
    toastNoteSaved: "अनुसंधान नोट ड्राफ्ट स्टैक पर सफलतापूर्वक सहेजा गया।",
    toastFeedbackSaved: "उपयोग करने के लिए धन्यवाद! आपकी मूल्यवान प्रतिक्रिया सफलतापूर्वक सबमिट कर दी गई है।",
    regeneratePortrait: "चित्र फिर से बनाएं",
    generatePortrait: "चित्र उत्पन्न करें",
    wikipediaBio: "विकिपीडिया जीवनी",
    activeLanguage: "भाषा प्रदर्शित करें",
    selectFontLabel: "सौंदर्यपूर्ण टाइपोग्राफी फ़ॉन्ट",
  },
  fr: {
    appName: "Scientia Confluxus",
    subtitle: "Recherchez une anomalie scientifique, un jalon historique ou une formule physique pour synthétiser des dossiers chronologiques personnalisés et des rapports de laboratoire.",
    searchPlaceholder: "Entrez un sujet de recherche (ex: Gravité Quantique)...",
    synthesizeBtn: "Synthétiser le Dossier",
    academicDesk: "Bureau Académique",
    shareLinkBtn: "Partager le Lien",
    controlCenter: "Centre de Contrôle Scientia",
    researchDeskTab: "Bureau Académique",
    prefTab: "Préférences & Aide",
    themeShift: "Changements de Thème Visuel",
    themeDescription: "Personnalisez dynamiquement l'ensemble de la palette de couleurs de l'application pour des recherches académiques confortables de jour comme de nuit :",
    scholarContact: "Contact Chercheur",
    scholarDescription: "Connectez-vous directement avec l'Archiviste en Chef pour des soumissions collaboratives ou des demandes d'informations :",
    thanksTribute: "Merci d'utiliser Scientia Confluxus !",
    thanksDetailed: "Nous sommes dédiés à la création de synthèses intellectuelles de haute fidélité. Veuillez partager vos suggestions ou commentaires ci-dessous pour enrichir nos bases de connaissances.",
    commentsLabel: "Écrire des Commentaires & suggestions",
    submitComments: "Envoyer le Commentaire",
    commentsPlaceholder: "Saisissez vos suggestions, erreurs détectées, idées de base de données ou demandes de fonctionnalités...",
    recommendedTopics: "Recommandations Académiques Populaires",
    exploreTab: "Vue d'ensemble",
    chronologyTab: "Chronologie des Jalons",
    labLogTab: "Rapport de Laboratoire",
    readingsTab: "Revue de Littérature",
    toastNoteSaved: "Note de recherche enregistrée avec succès dans le brouillon.",
    toastFeedbackSaved: "Merci pour votre utilisation ! Vos précieux commentaires ont été transmis avec succès.",
    regeneratePortrait: "Régénérer Port",
    generatePortrait: "Générer Portrait",
    wikipediaBio: "Biographie Wikipédia",
    activeLanguage: "Langue d'affichage",
    selectFontLabel: "Police Typographique d'Esthétique",
  },
  es: {
    appName: "Scientia Confluxus",
    subtitle: "Busque una anomalía científica, un hito histórico o una fórmula física para sintetizar expedientes cronológicos personalizados y registros de laboratorio.",
    searchPlaceholder: "Ingrese un tema de investigación (ej. Gravedad Cuántica)...",
    synthesizeBtn: "Sintetizar Expediente",
    academicDesk: "Escritorio Académico",
    shareLinkBtn: "Compartir Enlace",
    controlCenter: "Centro de Control de Scientia",
    researchDeskTab: "Escritorio Académico",
    prefTab: "Preferencias y Ayuda",
    themeShift: "Cambios de Tema Visual",
    themeDescription: "Personalice dinámicamente todo el esquema de colores de la plataforma para una investigación académica cómoda de día o de noche:",
    scholarContact: "Contacto del Académico",
    scholarDescription: "Conéctese directamente con el Archivista Jefe para envíos colaborativos o consultas sobre conjuntos de datos:",
    thanksTribute: "¡Gracias por usar Scientia Confluxus!",
    thanksDetailed: "Nos dedicamos a construir síntesis intelectuales de alta fidelidad. Comparta sus sugerencias o comentarios a continuación para que podamos ampliar nuestros registros científicos.",
    commentsLabel: "Escribir Comentarios y sugerencias",
    submitComments: "Enviar Comentarios",
    commentsPlaceholder: "Ingrese sugerencias, errores detectados, ideas de bases de datos o solicitudes de funciones...",
    recommendedTopics: "Recomendaciones Académicas Populares",
    exploreTab: "Resumen de Exploración",
    chronologyTab: "Cronología de Hitos",
    labLogTab: "Registro de Laboratorio",
    readingsTab: "Revisión de Literatura",
    toastNoteSaved: "Nota de investigación memorizada con éxito en el borrador.",
    toastFeedbackSaved: "¡Gracias por usar la app! Su valiosa opinión ha sido entregada con éxito.",
    regeneratePortrait: "Regenerar Retrato",
    generatePortrait: "Gen Retrato",
    wikipediaBio: "Biografía de Wikipedia",
    activeLanguage: "Idioma de pantalla",
    selectFontLabel: "Fuente Tipográfica Estética",
  },
  zh: {
    appName: "科学汇流 (Scientia Confluxus)",
    subtitle: "搜索科学异常、历史里程碑或物理公式，合成定制的时间轴研究档案和实验室状态日志。",
    searchPlaceholder: "输入研究课题（例如：量子重力）...",
    synthesizeBtn: "合成学术档案",
    academicDesk: "学术书案",
    shareLinkBtn: "分享链接",
    controlCenter: "科学控制中心",
    researchDeskTab: "学术书案",
    prefTab: "偏好与帮助",
    themeShift: "背景主题切换",
    themeDescription: "动态定制应用平台的完整配色方案，提供舒适的白天或夜间学术研究体验：",
    scholarContact: "学者联系方式",
    scholarDescription: "直接与首席档案保管员取得联系，进行合作提交或数据集咨询：",
    thanksTribute: "感谢您使用科学汇流！",
    thanksDetailed: "我们致力于构建高保真度的知识合成系统。请在下方分享您的宝贵建议或反馈，以便我们扩展学术知识库。",
    commentsLabel: "填写意见与建议",
    submitComments: "提交反馈意见",
    commentsPlaceholder: "输入您的建议、发现的错误、数据库想法或功能请求...",
    recommendedTopics: "热门学术研究推荐",
    exploreTab: "探索总览",
    chronologyTab: "里程碑编年史",
    labLogTab: "实验室状态日志",
    readingsTab: "文献综述",
    toastNoteSaved: "研究便签已成功保存在草稿堆栈中。",
    toastFeedbackSaved: "感谢您的使用！您的宝贵意见已成功提交。",
    regeneratePortrait: "重新生成肖像",
    generatePortrait: "生成学术肖像",
    wikipediaBio: "维基百科传记",
    activeLanguage: "显示语言选择",
    selectFontLabel: "审美排版字体样式",
  },
  hinglish: {
    appName: "Scientia Confluxus (Hinglish)",
    subtitle: "Search kijiye koi bhi scientific anomaly, historical milestone ya physical formula custom chronological dossiers aur laboratory status logs synthesize karne ke liye.",
    searchPlaceholder: "Research topic enter karein (jaise, Quantum Gravity)...",
    synthesizeBtn: "Dossier Synthesize Karein",
    academicDesk: "Academic Desk",
    shareLinkBtn: "Link Share Karein",
    controlCenter: "Scientia Control Center",
    researchDeskTab: "Academic Desk",
    prefTab: "Preferences & Help",
    themeShift: "Background Theme Shifts",
    themeDescription: "Apne comfort ke hisab se day ya night academic research ke liye application platform ka color scheme badlein:",
    scholarContact: "Scholar Se Contact",
    scholarDescription: "Chief Archivist se directly connect karein collaborations ya datasets queries ke liye:",
    thanksTribute: "Scientia Confluxus use karne ke liye dhanyawaad!",
    thanksDetailed: "Hum high-fidelity intellectual syntheses banane ke liye dedicated hain. Please apne suggestions ya comments neeche share karein taaki hum scientific knowledge logs ko expand kar sakein.",
    commentsLabel: "Apne Comments & suggestions likhein",
    submitComments: "Comments Submit Karein",
    commentsPlaceholder: "Suggestions, errors detected, database ideas, ya feature requests dalein...",
    recommendedTopics: "Popular Scholarly Recommendations",
    exploreTab: "Explore Overview",
    chronologyTab: "Milestone Chronology",
    labLogTab: "Lab Status Log",
    readingsTab: "Literature Review",
    toastNoteSaved: "Research note draft stack pe successfully save ho gayi hai.",
    toastFeedbackSaved: "Thank you! Aapka feedback successfully submit ho gaya hai.",
    regeneratePortrait: "Portrait Re-generate Karein",
    generatePortrait: "Portrait Banayein",
    wikipediaBio: "Wikipedia Biography",
    activeLanguage: "Display Language",
    selectFontLabel: "Aesthetic Typography Font",
  }
};
